// <auto-generated />
using System;
using AllPolicyInsurance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllPolicyInsurance.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220215200227_Create Schema and DB seeding")]
    partial class CreateSchemaandDBseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("InsurancePolicyId")
                        .IsUnique();

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Cincinatti",
                            InsurancePolicyId = 863871,
                            PostalCode = "45215",
                            State = "OH",
                            Street = "123 Main St"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Cincinatti",
                            InsurancePolicyId = 319655,
                            PostalCode = "45203",
                            State = "OH",
                            Street = "77 Elm Avenue"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Las Vegas",
                            InsurancePolicyId = 399217,
                            PostalCode = "89105",
                            State = "NV",
                            Street = "702 Flamingo Rd"
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Henderson",
                            InsurancePolicyId = 769245,
                            PostalCode = "89119",
                            State = "NV",
                            Street = "21 Tropicana Ave"
                        },
                        new
                        {
                            AddressId = 5,
                            City = "San Fransisco",
                            InsurancePolicyId = 972348,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "88 Haight St"
                        },
                        new
                        {
                            AddressId = 6,
                            City = "San Fransisco",
                            InsurancePolicyId = 109164,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "420 Ashbury"
                        },
                        new
                        {
                            AddressId = 7,
                            City = "Oakland",
                            InsurancePolicyId = 134365,
                            PostalCode = "94604",
                            State = "CA",
                            Street = "570 Pharcyde Lane"
                        },
                        new
                        {
                            AddressId = 8,
                            City = "Oakland",
                            InsurancePolicyId = 710259,
                            PostalCode = "94616",
                            State = "CA",
                            Street = "E. 40 Major Way "
                        },
                        new
                        {
                            AddressId = 9,
                            City = "Los Angeles",
                            InsurancePolicyId = 380041,
                            PostalCode = "90210",
                            State = "CA",
                            Street = "88 Pacific Overlook Blvd"
                        },
                        new
                        {
                            AddressId = 10,
                            City = "Newport",
                            InsurancePolicyId = 788741,
                            PostalCode = "90004",
                            State = "CA",
                            Street = "8 Mamba Street"
                        },
                        new
                        {
                            AddressId = 11,
                            City = "Brooklyn",
                            InsurancePolicyId = 253905,
                            PostalCode = "11211",
                            State = "NY",
                            Street = "123 Fulton Street"
                        },
                        new
                        {
                            AddressId = 12,
                            City = "Brooklyn",
                            InsurancePolicyId = 558865,
                            PostalCode = "11206",
                            State = "NY",
                            Street = "1120 Flatbush Ave "
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DriversLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PremiumPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PolicyId");

                    b.ToTable("InsurancePolicies");

                    b.HasData(
                        new
                        {
                            PolicyId = 863871,
                            DriversLicenseNumber = "50725819",
                            EffectiveDate = new DateTime(2022, 1, 16, 12, 2, 27, 257, DateTimeKind.Local).AddTicks(369),
                            ExpirationDate = new DateTime(2024, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(2491),
                            FirstName = "Joe",
                            LastName = "Burrow",
                            PremiumPrice = 350.0m
                        },
                        new
                        {
                            PolicyId = 319655,
                            DriversLicenseNumber = "85190713",
                            EffectiveDate = new DateTime(2021, 4, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4076),
                            ExpirationDate = new DateTime(2025, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4092),
                            FirstName = "Ja'Marr",
                            LastName = "Chase",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 399217,
                            DriversLicenseNumber = "74907111",
                            EffectiveDate = new DateTime(2014, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4107),
                            ExpirationDate = new DateTime(2018, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4110),
                            FirstName = "Mark",
                            LastName = "Stone",
                            PremiumPrice = 145.0m
                        },
                        new
                        {
                            PolicyId = 769245,
                            DriversLicenseNumber = "72600482",
                            EffectiveDate = new DateTime(2019, 11, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4114),
                            ExpirationDate = new DateTime(2021, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4117),
                            FirstName = "Larry",
                            LastName = "Johnson",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 972348,
                            DriversLicenseNumber = "15100935",
                            EffectiveDate = new DateTime(2021, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4120),
                            ExpirationDate = new DateTime(2025, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4122),
                            FirstName = "Steph",
                            LastName = "Curry",
                            PremiumPrice = 315.0m
                        },
                        new
                        {
                            PolicyId = 109164,
                            DriversLicenseNumber = "43283972",
                            EffectiveDate = new DateTime(2022, 1, 16, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4126),
                            ExpirationDate = new DateTime(2027, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4128),
                            FirstName = "Draymond",
                            LastName = "Green",
                            PremiumPrice = 200.0m
                        },
                        new
                        {
                            PolicyId = 134365,
                            DriversLicenseNumber = "60933490",
                            EffectiveDate = new DateTime(2014, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4132),
                            ExpirationDate = new DateTime(2020, 6, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4134),
                            FirstName = "Andrew",
                            LastName = "Wiggins",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 710259,
                            DriversLicenseNumber = "48275090",
                            EffectiveDate = new DateTime(2020, 11, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4138),
                            ExpirationDate = new DateTime(2025, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4141),
                            FirstName = "Debo",
                            LastName = "Samuel",
                            PremiumPrice = 345.0m
                        },
                        new
                        {
                            PolicyId = 380041,
                            DriversLicenseNumber = "42720420",
                            EffectiveDate = new DateTime(2016, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4145),
                            ExpirationDate = new DateTime(2021, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4148),
                            FirstName = "Cooper",
                            LastName = "Kupp",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 788741,
                            DriversLicenseNumber = "44321177",
                            EffectiveDate = new DateTime(2016, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4151),
                            ExpirationDate = new DateTime(2021, 2, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4154),
                            FirstName = "Kobe",
                            LastName = "Bryant",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 253905,
                            DriversLicenseNumber = "56200559",
                            EffectiveDate = new DateTime(2022, 1, 31, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4157),
                            ExpirationDate = new DateTime(2025, 10, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4159),
                            FirstName = "Kyrie",
                            LastName = "Irving",
                            PremiumPrice = 311.0m
                        },
                        new
                        {
                            PolicyId = 558865,
                            DriversLicenseNumber = "79062485",
                            EffectiveDate = new DateTime(2020, 9, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4163),
                            ExpirationDate = new DateTime(2024, 8, 15, 12, 2, 27, 259, DateTimeKind.Local).AddTicks(4166),
                            FirstName = "Kevin",
                            LastName = "Durant",
                            PremiumPrice = 420.0m
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("VehicleId");

                    b.HasIndex("InsurancePolicyId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            InsurancePolicyId = 863871,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 2,
                            InsurancePolicyId = 863871,
                            Make = "BMW",
                            Model = "Z4",
                            Year = "2008"
                        },
                        new
                        {
                            VehicleId = 3,
                            InsurancePolicyId = 863871,
                            Make = "GMC",
                            Model = "Suburban",
                            Year = "2014"
                        },
                        new
                        {
                            VehicleId = 4,
                            InsurancePolicyId = 319655,
                            Make = "Porsche",
                            Model = "Macan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 5,
                            InsurancePolicyId = 399217,
                            Make = "Ford",
                            Model = "Mustang",
                            Year = "1966"
                        },
                        new
                        {
                            VehicleId = 6,
                            InsurancePolicyId = 769245,
                            Make = "Dodge",
                            Model = "Viper",
                            Year = "1995"
                        },
                        new
                        {
                            VehicleId = 7,
                            InsurancePolicyId = 972348,
                            Make = "Mercedes-benz",
                            Model = "SL-63",
                            Year = "2019"
                        },
                        new
                        {
                            VehicleId = 8,
                            InsurancePolicyId = 972348,
                            Make = "Acura",
                            Model = "NSX",
                            Year = "1990"
                        },
                        new
                        {
                            VehicleId = 9,
                            InsurancePolicyId = 109164,
                            Make = "Oldsmobile",
                            Model = "Cutlass",
                            Year = "1967"
                        },
                        new
                        {
                            VehicleId = 10,
                            InsurancePolicyId = 134365,
                            Make = "Shelby",
                            Model = "G.T. 350",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 11,
                            InsurancePolicyId = 710259,
                            Make = "BMW",
                            Model = "M6",
                            Year = "2021"
                        },
                        new
                        {
                            VehicleId = 12,
                            InsurancePolicyId = 380041,
                            Make = "Chevrolet",
                            Model = "Tahoe",
                            Year = "1993"
                        },
                        new
                        {
                            VehicleId = 13,
                            InsurancePolicyId = 788741,
                            Make = "McLaren",
                            Model = "F1",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 14,
                            InsurancePolicyId = 253905,
                            Make = "Lamborghini",
                            Model = "Huracan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 15,
                            InsurancePolicyId = 558865,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2021"
                        },
                        new
                        {
                            VehicleId = 16,
                            InsurancePolicyId = 558865,
                            Make = "Porsche",
                            Model = "911 Turbo S",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 17,
                            InsurancePolicyId = 558865,
                            Make = "Chevrolet",
                            Model = "Corvette Sting Ray",
                            Year = "1963"
                        },
                        new
                        {
                            VehicleId = 18,
                            InsurancePolicyId = 558865,
                            Make = "Aston Martin",
                            Model = "DB4 GT Zagato",
                            Year = "1960"
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithOne("Address")
                        .HasForeignKey("AllPolicyInsurance.Models.Address", "InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithMany("Vehicles")
                        .HasForeignKey("InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
