// <auto-generated />
using System;
using AllPolicyInsurance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllPolicyInsurance.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220216220028_Create Schema and DB seeding")]
    partial class CreateSchemaandDBseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("InsurancePolicyId")
                        .IsUnique();

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Cincinatti",
                            InsurancePolicyId = 324822,
                            PostalCode = "45215",
                            State = "OH",
                            Street = "123 Main St"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Cincinatti",
                            InsurancePolicyId = 427132,
                            PostalCode = "45203",
                            State = "OH",
                            Street = "77 Elm Avenue"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Las Vegas",
                            InsurancePolicyId = 277347,
                            PostalCode = "89105",
                            State = "NV",
                            Street = "702 Flamingo Rd"
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Henderson",
                            InsurancePolicyId = 757023,
                            PostalCode = "89119",
                            State = "NV",
                            Street = "21 Tropicana Ave"
                        },
                        new
                        {
                            AddressId = 5,
                            City = "San Fransisco",
                            InsurancePolicyId = 318823,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "88 Haight St"
                        },
                        new
                        {
                            AddressId = 6,
                            City = "San Fransisco",
                            InsurancePolicyId = 896816,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "420 Ashbury"
                        },
                        new
                        {
                            AddressId = 7,
                            City = "Oakland",
                            InsurancePolicyId = 158000,
                            PostalCode = "94604",
                            State = "CA",
                            Street = "570 Pharcyde Lane"
                        },
                        new
                        {
                            AddressId = 8,
                            City = "Oakland",
                            InsurancePolicyId = 552054,
                            PostalCode = "94616",
                            State = "CA",
                            Street = "E. 40 Major Way "
                        },
                        new
                        {
                            AddressId = 9,
                            City = "Los Angeles",
                            InsurancePolicyId = 842518,
                            PostalCode = "90210",
                            State = "CA",
                            Street = "88 Pacific Overlook Blvd"
                        },
                        new
                        {
                            AddressId = 10,
                            City = "Newport",
                            InsurancePolicyId = 529256,
                            PostalCode = "90004",
                            State = "CA",
                            Street = "8 Mamba Street"
                        },
                        new
                        {
                            AddressId = 11,
                            City = "Brooklyn",
                            InsurancePolicyId = 528124,
                            PostalCode = "11211",
                            State = "NY",
                            Street = "123 Fulton Street"
                        },
                        new
                        {
                            AddressId = 12,
                            City = "Brooklyn",
                            InsurancePolicyId = 978371,
                            PostalCode = "11206",
                            State = "NY",
                            Street = "1120 Flatbush Ave "
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DriversLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PremiumPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PolicyId");

                    b.ToTable("InsurancePolicies");

                    b.HasData(
                        new
                        {
                            PolicyId = 324822,
                            DriversLicenseNumber = "42787182",
                            EffectiveDate = new DateTime(2022, 1, 17, 14, 0, 28, 553, DateTimeKind.Local).AddTicks(5404),
                            ExpirationDate = new DateTime(2024, 2, 16, 14, 0, 28, 555, DateTimeKind.Local).AddTicks(8504),
                            FirstName = "Joe",
                            LastName = "Burrow",
                            PremiumPrice = 350.0m
                        },
                        new
                        {
                            PolicyId = 427132,
                            DriversLicenseNumber = "11761117",
                            EffectiveDate = new DateTime(2021, 4, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(17),
                            ExpirationDate = new DateTime(2025, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(33),
                            FirstName = "Ja'Marr",
                            LastName = "Chase",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 277347,
                            DriversLicenseNumber = "62157047",
                            EffectiveDate = new DateTime(2014, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(49),
                            ExpirationDate = new DateTime(2018, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(52),
                            FirstName = "Mark",
                            LastName = "Stone",
                            PremiumPrice = 145.0m
                        },
                        new
                        {
                            PolicyId = 757023,
                            DriversLicenseNumber = "55467224",
                            EffectiveDate = new DateTime(2019, 11, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(56),
                            ExpirationDate = new DateTime(2021, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(58),
                            FirstName = "Larry",
                            LastName = "Johnson",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 318823,
                            DriversLicenseNumber = "97786428",
                            EffectiveDate = new DateTime(2021, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(62),
                            ExpirationDate = new DateTime(2025, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(64),
                            FirstName = "Steph",
                            LastName = "Curry",
                            PremiumPrice = 315.0m
                        },
                        new
                        {
                            PolicyId = 896816,
                            DriversLicenseNumber = "94649186",
                            EffectiveDate = new DateTime(2022, 1, 17, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(67),
                            ExpirationDate = new DateTime(2027, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(70),
                            FirstName = "Draymond",
                            LastName = "Green",
                            PremiumPrice = 200.0m
                        },
                        new
                        {
                            PolicyId = 158000,
                            DriversLicenseNumber = "80950036",
                            EffectiveDate = new DateTime(2014, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(73),
                            ExpirationDate = new DateTime(2020, 6, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(75),
                            FirstName = "Andrew",
                            LastName = "Wiggins",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 552054,
                            DriversLicenseNumber = "23704829",
                            EffectiveDate = new DateTime(2020, 11, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(79),
                            ExpirationDate = new DateTime(2025, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(85),
                            FirstName = "Debo",
                            LastName = "Samuel",
                            PremiumPrice = 345.0m
                        },
                        new
                        {
                            PolicyId = 842518,
                            DriversLicenseNumber = "65795804",
                            EffectiveDate = new DateTime(2016, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(88),
                            ExpirationDate = new DateTime(2021, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(90),
                            FirstName = "Cooper",
                            LastName = "Kupp",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 529256,
                            DriversLicenseNumber = "90265009",
                            EffectiveDate = new DateTime(2016, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(94),
                            ExpirationDate = new DateTime(2021, 2, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(96),
                            FirstName = "Kobe",
                            LastName = "Bryant",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 528124,
                            DriversLicenseNumber = "68129724",
                            EffectiveDate = new DateTime(2022, 2, 1, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(99),
                            ExpirationDate = new DateTime(2025, 10, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(101),
                            FirstName = "Kyrie",
                            LastName = "Irving",
                            PremiumPrice = 311.0m
                        },
                        new
                        {
                            PolicyId = 978371,
                            DriversLicenseNumber = "02871370",
                            EffectiveDate = new DateTime(2020, 9, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(105),
                            ExpirationDate = new DateTime(2024, 8, 16, 14, 0, 28, 556, DateTimeKind.Local).AddTicks(107),
                            FirstName = "Kevin",
                            LastName = "Durant",
                            PremiumPrice = 420.0m
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("VehicleId");

                    b.HasIndex("InsurancePolicyId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            InsurancePolicyId = 324822,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 2,
                            InsurancePolicyId = 324822,
                            Make = "BMW",
                            Model = "Z4",
                            Year = "2008"
                        },
                        new
                        {
                            VehicleId = 3,
                            InsurancePolicyId = 324822,
                            Make = "GMC",
                            Model = "Suburban",
                            Year = "2014"
                        },
                        new
                        {
                            VehicleId = 4,
                            InsurancePolicyId = 427132,
                            Make = "Porsche",
                            Model = "Macan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 5,
                            InsurancePolicyId = 277347,
                            Make = "Ford",
                            Model = "Mustang",
                            Year = "1966"
                        },
                        new
                        {
                            VehicleId = 6,
                            InsurancePolicyId = 757023,
                            Make = "Dodge",
                            Model = "Viper",
                            Year = "1995"
                        },
                        new
                        {
                            VehicleId = 7,
                            InsurancePolicyId = 318823,
                            Make = "Mercedes-benz",
                            Model = "SL-63",
                            Year = "2019"
                        },
                        new
                        {
                            VehicleId = 8,
                            InsurancePolicyId = 318823,
                            Make = "Acura",
                            Model = "NSX",
                            Year = "1990"
                        },
                        new
                        {
                            VehicleId = 9,
                            InsurancePolicyId = 896816,
                            Make = "Oldsmobile",
                            Model = "Cutlass",
                            Year = "1967"
                        },
                        new
                        {
                            VehicleId = 10,
                            InsurancePolicyId = 158000,
                            Make = "Shelby",
                            Model = "G.T. 350",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 11,
                            InsurancePolicyId = 552054,
                            Make = "BMW",
                            Model = "M6",
                            Year = "2021"
                        },
                        new
                        {
                            VehicleId = 12,
                            InsurancePolicyId = 842518,
                            Make = "Chevrolet",
                            Model = "Tahoe",
                            Year = "1993"
                        },
                        new
                        {
                            VehicleId = 13,
                            InsurancePolicyId = 529256,
                            Make = "McLaren",
                            Model = "F1",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 14,
                            InsurancePolicyId = 528124,
                            Make = "Lamborghini",
                            Model = "Huracan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 15,
                            InsurancePolicyId = 978371,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2021"
                        },
                        new
                        {
                            VehicleId = 16,
                            InsurancePolicyId = 978371,
                            Make = "Porsche",
                            Model = "911 Turbo S",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 17,
                            InsurancePolicyId = 978371,
                            Make = "Chevrolet",
                            Model = "Corvette Sting Ray",
                            Year = "1963"
                        },
                        new
                        {
                            VehicleId = 18,
                            InsurancePolicyId = 978371,
                            Make = "Aston Martin",
                            Model = "DB4 GT Zagato",
                            Year = "1960"
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithOne("Address")
                        .HasForeignKey("AllPolicyInsurance.Models.Address", "InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithMany("Vehicles")
                        .HasForeignKey("InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
