// <auto-generated />
using System;
using AllPolicyInsurance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllPolicyInsurance.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("InsurancePolicyId")
                        .IsUnique();

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Cincinatti",
                            InsurancePolicyId = 739646,
                            PostalCode = "45215",
                            State = "OH",
                            Street = "123 Main St"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Cincinatti",
                            InsurancePolicyId = 716287,
                            PostalCode = "45203",
                            State = "OH",
                            Street = "77 Elm Avenue"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Las Vegas",
                            InsurancePolicyId = 705889,
                            PostalCode = "89105",
                            State = "NV",
                            Street = "702 Flamingo Rd"
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Henderson",
                            InsurancePolicyId = 582222,
                            PostalCode = "89119",
                            State = "NV",
                            Street = "21 Tropicana Ave"
                        },
                        new
                        {
                            AddressId = 5,
                            City = "San Fransisco",
                            InsurancePolicyId = 637769,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "88 Haight St"
                        },
                        new
                        {
                            AddressId = 6,
                            City = "San Fransisco",
                            InsurancePolicyId = 705683,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "420 Ashbury"
                        },
                        new
                        {
                            AddressId = 7,
                            City = "Oakland",
                            InsurancePolicyId = 827976,
                            PostalCode = "94604",
                            State = "CA",
                            Street = "570 Pharcyde Lane"
                        },
                        new
                        {
                            AddressId = 8,
                            City = "Oakland",
                            InsurancePolicyId = 945703,
                            PostalCode = "94616",
                            State = "CA",
                            Street = "E. 40 Major Way "
                        },
                        new
                        {
                            AddressId = 9,
                            City = "Los Angeles",
                            InsurancePolicyId = 517229,
                            PostalCode = "90210",
                            State = "CA",
                            Street = "88 Pacific Overlook Blvd"
                        },
                        new
                        {
                            AddressId = 10,
                            City = "Newport",
                            InsurancePolicyId = 912358,
                            PostalCode = "90004",
                            State = "CA",
                            Street = "8 Mamba Street"
                        },
                        new
                        {
                            AddressId = 11,
                            City = "Brooklyn",
                            InsurancePolicyId = 468308,
                            PostalCode = "11211",
                            State = "NY",
                            Street = "123 Fulton Street"
                        },
                        new
                        {
                            AddressId = 12,
                            City = "Brooklyn",
                            InsurancePolicyId = 740556,
                            PostalCode = "11206",
                            State = "NY",
                            Street = "1120 Flatbush Ave "
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DriversLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PremiumPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PolicyId");

                    b.ToTable("InsurancePolicies");

                    b.HasData(
                        new
                        {
                            PolicyId = 739646,
                            DriversLicenseNumber = "54114066",
                            EffectiveDate = new DateTime(2022, 1, 16, 7, 49, 23, 31, DateTimeKind.Local).AddTicks(3842),
                            ExpirationDate = new DateTime(2024, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(6151),
                            FirstName = "Joe",
                            LastName = "Burrow",
                            PremiumPrice = 350.0m
                        },
                        new
                        {
                            PolicyId = 716287,
                            DriversLicenseNumber = "93445810",
                            EffectiveDate = new DateTime(2021, 4, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7676),
                            ExpirationDate = new DateTime(2025, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7694),
                            FirstName = "Ja'Marr",
                            LastName = "Chase",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 705889,
                            DriversLicenseNumber = "91820223",
                            EffectiveDate = new DateTime(2014, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7708),
                            ExpirationDate = new DateTime(2018, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7711),
                            FirstName = "Mark",
                            LastName = "Stone",
                            PremiumPrice = 145.0m
                        },
                        new
                        {
                            PolicyId = 582222,
                            DriversLicenseNumber = "70126605",
                            EffectiveDate = new DateTime(2019, 11, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7715),
                            ExpirationDate = new DateTime(2021, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7718),
                            FirstName = "Larry",
                            LastName = "Johnson",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 637769,
                            DriversLicenseNumber = "57688514",
                            EffectiveDate = new DateTime(2021, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7721),
                            ExpirationDate = new DateTime(2025, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7723),
                            FirstName = "Steph",
                            LastName = "Curry",
                            PremiumPrice = 315.0m
                        },
                        new
                        {
                            PolicyId = 705683,
                            DriversLicenseNumber = "28668068",
                            EffectiveDate = new DateTime(2022, 1, 16, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7726),
                            ExpirationDate = new DateTime(2027, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7728),
                            FirstName = "Draymond",
                            LastName = "Green",
                            PremiumPrice = 200.0m
                        },
                        new
                        {
                            PolicyId = 827976,
                            DriversLicenseNumber = "10319154",
                            EffectiveDate = new DateTime(2014, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7732),
                            ExpirationDate = new DateTime(2020, 6, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7734),
                            FirstName = "Andrew",
                            LastName = "Wiggins",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 945703,
                            DriversLicenseNumber = "49276028",
                            EffectiveDate = new DateTime(2020, 11, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7737),
                            ExpirationDate = new DateTime(2025, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7740),
                            FirstName = "Debo",
                            LastName = "Samuel",
                            PremiumPrice = 345.0m
                        },
                        new
                        {
                            PolicyId = 517229,
                            DriversLicenseNumber = "22838511",
                            EffectiveDate = new DateTime(2016, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7795),
                            ExpirationDate = new DateTime(2021, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7798),
                            FirstName = "Cooper",
                            LastName = "Kupp",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 912358,
                            DriversLicenseNumber = "35147137",
                            EffectiveDate = new DateTime(2016, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7802),
                            ExpirationDate = new DateTime(2021, 2, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7804),
                            FirstName = "Kobe",
                            LastName = "Bryant",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 468308,
                            DriversLicenseNumber = "33805986",
                            EffectiveDate = new DateTime(2022, 1, 31, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7807),
                            ExpirationDate = new DateTime(2025, 10, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7810),
                            FirstName = "Kyrie",
                            LastName = "Irving",
                            PremiumPrice = 311.0m
                        },
                        new
                        {
                            PolicyId = 740556,
                            DriversLicenseNumber = "86728178",
                            EffectiveDate = new DateTime(2020, 9, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7813),
                            ExpirationDate = new DateTime(2024, 8, 15, 7, 49, 23, 33, DateTimeKind.Local).AddTicks(7815),
                            FirstName = "Kevin",
                            LastName = "Durant",
                            PremiumPrice = 420.0m
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("VehicleId");

                    b.HasIndex("InsurancePolicyId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            InsurancePolicyId = 739646,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 2,
                            InsurancePolicyId = 739646,
                            Make = "GMC",
                            Model = "Suburban",
                            Year = "2014"
                        },
                        new
                        {
                            VehicleId = 3,
                            InsurancePolicyId = 739646,
                            Make = "BMW",
                            Model = "Z4",
                            Year = "2008"
                        },
                        new
                        {
                            VehicleId = 4,
                            InsurancePolicyId = 716287,
                            Make = "Porsche",
                            Model = "Macan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 5,
                            InsurancePolicyId = 705889,
                            Make = "Ford",
                            Model = "Mustang",
                            Year = "1966"
                        },
                        new
                        {
                            VehicleId = 6,
                            InsurancePolicyId = 582222,
                            Make = "Dodge",
                            Model = "Viper",
                            Year = "1995"
                        },
                        new
                        {
                            VehicleId = 7,
                            InsurancePolicyId = 637769,
                            Make = "Mercedes-benz",
                            Model = "SL-63",
                            Year = "2019"
                        },
                        new
                        {
                            VehicleId = 8,
                            InsurancePolicyId = 637769,
                            Make = "Acura",
                            Model = "NSX",
                            Year = "1990"
                        },
                        new
                        {
                            VehicleId = 9,
                            InsurancePolicyId = 705683,
                            Make = "Oldsmobile",
                            Model = "Cutlass",
                            Year = "1967"
                        },
                        new
                        {
                            VehicleId = 10,
                            InsurancePolicyId = 827976,
                            Make = "Shelby",
                            Model = "G.T. 350",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 11,
                            InsurancePolicyId = 945703,
                            Make = "BMW",
                            Model = "M6",
                            Year = "2021"
                        },
                        new
                        {
                            VehicleId = 12,
                            InsurancePolicyId = 517229,
                            Make = "Chevrolet",
                            Model = "Tahoe",
                            Year = "1993"
                        },
                        new
                        {
                            VehicleId = 13,
                            InsurancePolicyId = 912358,
                            Make = "McLaren",
                            Model = "F1",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 14,
                            InsurancePolicyId = 468308,
                            Make = "Lamborghini",
                            Model = "Huracan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 15,
                            InsurancePolicyId = 740556,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2021"
                        },
                        new
                        {
                            VehicleId = 16,
                            InsurancePolicyId = 740556,
                            Make = "Porsche",
                            Model = "911 Turbo S",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 17,
                            InsurancePolicyId = 740556,
                            Make = "Chevrolet",
                            Model = "Corvette Sting Ray",
                            Year = "1963"
                        },
                        new
                        {
                            VehicleId = 18,
                            InsurancePolicyId = 740556,
                            Make = "Aston Martin",
                            Model = "DB4 GT Zagato",
                            Year = "1960"
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithOne("Address")
                        .HasForeignKey("AllPolicyInsurance.Models.Address", "InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithMany("Vehicles")
                        .HasForeignKey("InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
