// <auto-generated />
using System;
using AllPolicyInsurance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllPolicyInsurance.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("InsurancePolicyId")
                        .IsUnique();

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Cincinatti",
                            InsurancePolicyId = 329033,
                            PostalCode = "45215",
                            State = "OH",
                            Street = "123 Main St"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Cincinatti",
                            InsurancePolicyId = 398210,
                            PostalCode = "45203",
                            State = "OH",
                            Street = "77 Elm Avenue"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Las Vegas",
                            InsurancePolicyId = 553982,
                            PostalCode = "89105",
                            State = "NV",
                            Street = "702 Flamingo Rd"
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Henderson",
                            InsurancePolicyId = 162048,
                            PostalCode = "89119",
                            State = "NV",
                            Street = "21 Tropicana Ave"
                        },
                        new
                        {
                            AddressId = 5,
                            City = "San Fransisco",
                            InsurancePolicyId = 457727,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "88 Haight St"
                        },
                        new
                        {
                            AddressId = 6,
                            City = "San Fransisco",
                            InsurancePolicyId = 934795,
                            PostalCode = "94117",
                            State = "CA",
                            Street = "420 Ashbury"
                        },
                        new
                        {
                            AddressId = 7,
                            City = "Oakland",
                            InsurancePolicyId = 555816,
                            PostalCode = "94604",
                            State = "CA",
                            Street = "570 Pharcyde Lane"
                        },
                        new
                        {
                            AddressId = 8,
                            City = "Oakland",
                            InsurancePolicyId = 988010,
                            PostalCode = "94616",
                            State = "CA",
                            Street = "E. 40 Major Way "
                        },
                        new
                        {
                            AddressId = 9,
                            City = "Los Angeles",
                            InsurancePolicyId = 539139,
                            PostalCode = "90210",
                            State = "CA",
                            Street = "88 Pacific Overlook Blvd"
                        },
                        new
                        {
                            AddressId = 10,
                            City = "Newport",
                            InsurancePolicyId = 716879,
                            PostalCode = "90004",
                            State = "CA",
                            Street = "8 Mamba Street"
                        },
                        new
                        {
                            AddressId = 11,
                            City = "Brooklyn",
                            InsurancePolicyId = 596124,
                            PostalCode = "11211",
                            State = "NY",
                            Street = "123 Fulton Street"
                        },
                        new
                        {
                            AddressId = 12,
                            City = "Brooklyn",
                            InsurancePolicyId = 661511,
                            PostalCode = "11206",
                            State = "NY",
                            Street = "1120 Flatbush Ave "
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DriversLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PremiumPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PolicyId");

                    b.ToTable("InsurancePolicies");

                    b.HasData(
                        new
                        {
                            PolicyId = 329033,
                            DriversLicenseNumber = "88334554",
                            EffectiveDate = new DateTime(2022, 1, 15, 12, 25, 46, 381, DateTimeKind.Local).AddTicks(6384),
                            ExpirationDate = new DateTime(2024, 2, 14, 12, 25, 46, 383, DateTimeKind.Local).AddTicks(9156),
                            FirstName = "Joe",
                            LastName = "Burrow",
                            PremiumPrice = 350.0m
                        },
                        new
                        {
                            PolicyId = 398210,
                            DriversLicenseNumber = "60141428",
                            EffectiveDate = new DateTime(2021, 4, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(665),
                            ExpirationDate = new DateTime(2025, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(681),
                            FirstName = "Ja'Marr",
                            LastName = "Chase",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 553982,
                            DriversLicenseNumber = "04092046",
                            EffectiveDate = new DateTime(2014, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(696),
                            ExpirationDate = new DateTime(2018, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(699),
                            FirstName = "Mark",
                            LastName = "Stone",
                            PremiumPrice = 145.0m
                        },
                        new
                        {
                            PolicyId = 162048,
                            DriversLicenseNumber = "73824913",
                            EffectiveDate = new DateTime(2019, 11, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(751),
                            ExpirationDate = new DateTime(2021, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(754),
                            FirstName = "Larry",
                            LastName = "Johnson",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 457727,
                            DriversLicenseNumber = "34180223",
                            EffectiveDate = new DateTime(2021, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(757),
                            ExpirationDate = new DateTime(2025, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(759),
                            FirstName = "Steph",
                            LastName = "Curry",
                            PremiumPrice = 315.0m
                        },
                        new
                        {
                            PolicyId = 934795,
                            DriversLicenseNumber = "99503409",
                            EffectiveDate = new DateTime(2022, 1, 15, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(763),
                            ExpirationDate = new DateTime(2027, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(765),
                            FirstName = "Draymond",
                            LastName = "Green",
                            PremiumPrice = 200.0m
                        },
                        new
                        {
                            PolicyId = 555816,
                            DriversLicenseNumber = "52347333",
                            EffectiveDate = new DateTime(2014, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(768),
                            ExpirationDate = new DateTime(2020, 6, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(770),
                            FirstName = "Andrew",
                            LastName = "Wiggins",
                            PremiumPrice = 225.0m
                        },
                        new
                        {
                            PolicyId = 988010,
                            DriversLicenseNumber = "54106900",
                            EffectiveDate = new DateTime(2020, 11, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(774),
                            ExpirationDate = new DateTime(2025, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(776),
                            FirstName = "Debo",
                            LastName = "Samuel",
                            PremiumPrice = 345.0m
                        },
                        new
                        {
                            PolicyId = 539139,
                            DriversLicenseNumber = "21642779",
                            EffectiveDate = new DateTime(2016, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(780),
                            ExpirationDate = new DateTime(2021, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(782),
                            FirstName = "Cooper",
                            LastName = "Kupp",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 716879,
                            DriversLicenseNumber = "06269112",
                            EffectiveDate = new DateTime(2016, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(786),
                            ExpirationDate = new DateTime(2021, 2, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(788),
                            FirstName = "Kobe",
                            LastName = "Bryant",
                            PremiumPrice = 65.0m
                        },
                        new
                        {
                            PolicyId = 596124,
                            DriversLicenseNumber = "06023789",
                            EffectiveDate = new DateTime(2022, 1, 30, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(791),
                            ExpirationDate = new DateTime(2025, 10, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(793),
                            FirstName = "Kyrie",
                            LastName = "Irving",
                            PremiumPrice = 311.0m
                        },
                        new
                        {
                            PolicyId = 661511,
                            DriversLicenseNumber = "95007774",
                            EffectiveDate = new DateTime(2020, 9, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(796),
                            ExpirationDate = new DateTime(2024, 8, 14, 12, 25, 46, 384, DateTimeKind.Local).AddTicks(799),
                            FirstName = "Kevin",
                            LastName = "Durant",
                            PremiumPrice = 420.0m
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("VehicleId");

                    b.HasIndex("InsurancePolicyId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            InsurancePolicyId = 329033,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 2,
                            InsurancePolicyId = 398210,
                            Make = "Porsche",
                            Model = "Macan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 3,
                            InsurancePolicyId = 553982,
                            Make = "Ford",
                            Model = "Mustang",
                            Year = "1966"
                        },
                        new
                        {
                            VehicleId = 4,
                            InsurancePolicyId = 162048,
                            Make = "Dodge",
                            Model = "Viper",
                            Year = "1995"
                        },
                        new
                        {
                            VehicleId = 5,
                            InsurancePolicyId = 457727,
                            Make = "Mercedes-benz",
                            Model = "SL-63",
                            Year = "2019"
                        },
                        new
                        {
                            VehicleId = 6,
                            InsurancePolicyId = 934795,
                            Make = "Oldsmobile",
                            Model = "Cutlass",
                            Year = "1967"
                        },
                        new
                        {
                            VehicleId = 7,
                            InsurancePolicyId = 555816,
                            Make = "Shelby",
                            Model = "G.T. 350",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 8,
                            InsurancePolicyId = 988010,
                            Make = "BMW",
                            Model = "M6",
                            Year = "2021"
                        },
                        new
                        {
                            VehicleId = 9,
                            InsurancePolicyId = 539139,
                            Make = "Chevrolet",
                            Model = "Tahoe",
                            Year = "1993"
                        },
                        new
                        {
                            VehicleId = 10,
                            InsurancePolicyId = 716879,
                            Make = "McLaren",
                            Model = "F1",
                            Year = "2020"
                        },
                        new
                        {
                            VehicleId = 11,
                            InsurancePolicyId = 596124,
                            Make = "Lamborghini",
                            Model = "Huracan",
                            Year = "2022"
                        },
                        new
                        {
                            VehicleId = 12,
                            InsurancePolicyId = 661511,
                            Make = "Tesla",
                            Model = "Model X",
                            Year = "2021"
                        });
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Address", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithOne("Address")
                        .HasForeignKey("AllPolicyInsurance.Models.Address", "InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.Vehicle", b =>
                {
                    b.HasOne("AllPolicyInsurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithMany("Vehicles")
                        .HasForeignKey("InsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("AllPolicyInsurance.Models.InsurancePolicy", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
